server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.cq.cloud.api    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                       # mapper映射文件

spring:
  application:
    name: mycloud-dept                            #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3800/clouddb?characterEncoding=utf-8&&serverTimezone=UTC# 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: mycloud:8001
    prefer-ip-address: true
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: mycloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT
