server:
  port: 3344

spring:
  application:
    name:  mycloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:pengguoren/mycloud-config.git #GitHub上面的git仓库名字



